version: '3'

services:
  db:
    image: postgres
    healthcheck:
      test: "exit 0"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/tutor
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
